## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


Wee Jin Koh
ITP 449 HW2

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
import numpy as np
import pandas as pd


In [ ]:

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
#Q1-1
frame = pd.DataFrame(data)
print(frame)


     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


In [ ]:
#Q1-2
frame[((frame["job"]== "psychologist") | (frame["job"]== "teacher")) & (frame["num_cars"]> frame["family_size"])]


name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [ ]:
#Q1-3
frame[(frame["family_size"]<=2) & ( frame["num_cars"]> 0)]


name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

In [ ]:
#Q1-4
len(frame.job.unique())

4

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
#copied from prompt, and named the 2 series
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10), name="fruit")
weights = pd.Series(np.linspace(1, 10, 10), name="weights")

#set fruit as DataFrame, and join weights to it
fruit = pd.DataFrame(fruit)
df = fruit.join(weights)
#print dataframe for answer checking reference
print(df, "\n")

#create function for finding mean weights of each fruit
def meanWeightByFruit():
  #initiate counting variables
  appleCount = 0
  bananaCount = 0
  carrotCount = 0
  appleWeight = 0
  bananaWeight = 0
  carrotWeight = 0
  #use .index to loop
  for i in df.index:
    # if the index of fruit column is a particular fruit, add 1 to fruit count and add the weight to the fruit weight count
    if df["fruit"][i] == "apple":
      appleCount+=1
      appleWeight+=(df["weights"][i])
    elif df["fruit"][i] == "banana":
      bananaCount+=1
      bananaWeight+=(df["weights"][i])
    elif df["fruit"][i] == "carrot":
      carrotCount+=1
      carrotWeight+=(df["weights"][i])

  #calculate mean by taking total weight divided by number of fruits
  if appleCount > 0:
    appleMean = appleWeight/appleCount
  else:
    appleMean = 0

  if bananaCount > 0:
    bananaMean = bananaWeight/bananaCount
  else:
    bananaMean = 0
  
  if carrotCount > 0:
    carrotMean = carrotWeight/carrotCount
  else:
    carrotMean = 0
  #print results
  print("Mean apple weight:", appleMean)
  print("Mean banana weight:", bananaMean)
  print("Mean carrot weight:", carrotMean)
meanWeightByFruit()





    fruit  weights
0   apple      1.0
1   apple      2.0
2  carrot      3.0
3   apple      4.0
4  banana      5.0
5  carrot      6.0
6   apple      7.0
7  banana      8.0
8  carrot      9.0
9  banana     10.0 

Mean apple weight: 3.5
Mean banana weight: 7.666666666666667
Mean carrot weight: 6.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
#Q3-1
#convert course_name to list
newList = course_name.tolist()
#sort using argsort. TA Amulya mentioned that it is fine that the list does not sort alphabetically, since capital letters come before uncapitalized letters.
sortList = np.argsort(newList)
print(sortList)

#Q3-2
#check if each element starts with "P". Returns array with True if starts with "P" and false if not.
startsWithP = np.char.startswith(course_name, "P")
print(startsWithP)





[1 3 0 2 4]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532]) #DONE IN CLASS B4

In [ ]:
# Type your solution here
#Q4-1
#reverse student_id array, and print both original and reversed arrays
rev_student_id = student_id[::-1]
print("#Q4-1")
print("reversed array: ",rev_student_id)
print("original array: ",student_id, "\n")

#Q4-2
#sorted student_id and picked the 3 largest values from the sorted array
sorted_student_id = np.sort(student_id)
print("#Q4-2")
print("3 largest values: ",sorted_student_id[-1:-4:-1])

#Q4-1
reversed array:  [4532 5241 1682 1671 6230 5202 1023]
original array:  [1023 5202 6230 1671 1682 5241 4532] 

#Q4-2
3 largest values:  [6230 5241 5202]


**Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
#use arange to create array of 0 to 99
arr = np.arange(100)
#isolate numbers that are multiples of 3 or 5
index = np.where((arr%5==0)|(arr%3==0))
#convert array to list
getToList = 0
for i in index:
  getToList += i
  #add up the numbers in the list
  totalSum = 0
  for e in getToList:
    totalSum += e
#print answer
print(totalSum)


2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
#Q6.1
#copy prompt
import numpy as np 
 
arr = np.arange(12).reshape(3, 4) 
print("given array:") 
print(arr, "\n") 

#swap columns 1 and 2
arr[:, [2, 1]] = arr[:, [1, 2]] 
print("Q6.1: after column swaps:") 
print(arr, "\n")



given array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Q6.1: after column swaps:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]] 



In [ ]:
#Q6.2
#copy prompt
import numpy as np 
 
arr = np.arange(12).reshape(3, 4) 
print("given array:") 
print(arr, "\n") 

#swap rows 0 and 1
arr[[1, 0], :] = arr[[0, 1], :] 
print("Q6.2: after row swaps:") 
print(arr)

given array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Q6.2: after row swaps:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
